# backend/utils/rights_data.py
"""
Static legal rights data for Indian citizens.
Covers 10 categories, each with rights in simple language.
"""

RIGHTS_CATEGORIES = [
    {
        "id": "arrested",
        "icon": "👮",
        "title": "If You Are Arrested",
        "color": "#1e3a5f",
        "accent": "#3b82f6",
        "rights": [
            "You have the right to know WHY you are being arrested",
            "You cannot be arrested without a warrant for non-cognizable offences",
            "You must be produced before a magistrate within 24 hours of arrest",
            "You have the right to inform a family member or friend of your arrest",
            "You have the right to consult a lawyer of your choice immediately",
            "You have the right to free legal aid if you cannot afford a lawyer",
            "You cannot be tortured or physically harmed during custody",
            "You have the right to remain silent — anything you say can be used against you",
            "Women cannot be arrested after sunset and before sunrise (except in special cases)",
            "You must be given a copy of the FIR if you are named in it",
        ],
        "laws": ["Article 22, Constitution of India", "Section 50, CrPC", "D.K. Basu v. State of West Bengal (1997)"],
        "helpline": ("Police Complaints", "100")
    },
    {
        "id": "domestic_violence",
        "icon": "🏠",
        "title": "Domestic Violence Rights",
        "color": "#3b1f2b",
        "accent": "#f43f5e",
        "rights": [
            "You have the right to live in your shared household — husband CANNOT throw you out",
            "You can get a Protection Order from a magistrate within 3 days",
            "You are entitled to monetary relief for medical expenses, loss of earnings",
            "You have the right to custody of your children during proceedings",
            "Any form of abuse — physical, emotional, sexual, financial — is covered under law",
            "You can file a complaint at any police station (Zero FIR)",
            "You do not need a lawyer to file under Domestic Violence Act",
            "You can approach a Protection Officer in your district for free help",
            "Even live-in partners are covered under the Domestic Violence Act",
            "Your abuser can be ordered to pay you maintenance while case is ongoing",
        ],
        "laws": ["Protection of Women from Domestic Violence Act, 2005", "Section 498A, IPC", "S.R. Batra v. Taruna Batra (2006)"],
        "helpline": ("Women Helpline", "181")
    },
    {
        "id": "worker",
        "icon": "👷",
        "title": "Worker / Employee Rights",
        "color": "#1c3a1c",
        "accent": "#22c55e",
        "rights": [
            "You must receive your salary on time — delay is punishable",
            "You cannot be fired without 1 month notice or pay in lieu",
            "You are entitled to Provident Fund (PF) contributions from your employer",
            "Women are entitled to 26 weeks of paid maternity leave",
            "You cannot be made to work more than 8 hours a day / 48 hours a week",
            "Overtime must be paid at double the normal wage rate",
            "You have the right to form or join a trade union",
            "Sexual harassment at workplace is a criminal offence (POSH Act 2013)",
            "You can file a complaint with the Labour Commissioner for unpaid wages",
            "Contract workers and daily wage workers also have labour rights",
        ],
        "laws": ["Payment of Wages Act, 1936", "Maternity Benefit Act, 1961", "Industrial Disputes Act, 1947", "POSH Act, 2013"],
        "helpline": ("Labour Helpline", "1800-11-1019")
    },
    {
        "id": "tenant",
        "icon": "🏘️",
        "title": "Tenant Rights",
        "color": "#2d2510",
        "accent": "#f59e0b",
        "rights": [
            "Your landlord CANNOT forcibly evict you without a court order",
            "You are entitled to a receipt for every rent payment you make",
            "Rent cannot be increased arbitrarily — it must follow state Rent Control Act",
            "Your landlord must give proper notice before entering your premises",
            "Security deposit must be returned when you vacate (minus legitimate deductions)",
            "You have the right to basic amenities — water, electricity — not cut as coercion",
            "A verbal tenancy agreement also has legal validity",
            "You can approach Rent Control Court if evicted illegally",
            "Landlord cannot discriminate based on religion, caste, or food habits",
            "You have the right to sub-let if your agreement permits it",
        ],
        "laws": ["Rent Control Acts (state-wise)", "Transfer of Property Act, 1882", "Model Tenancy Act, 2021"],
        "helpline": ("Consumer Helpline", "1800-11-4000")
    },
    {
        "id": "consumer",
        "icon": "🛒",
        "title": "Consumer Rights",
        "color": "#1a2040",
        "accent": "#818cf8",
        "rights": [
            "You have the right to get a bill/receipt for every purchase",
            "You can return defective goods and demand a replacement or refund",
            "You can file a consumer complaint even for services — doctor, bank, builder",
            "Complaint can be filed online at edaakhil.nic.in — no lawyer needed",
            "You can claim compensation for mental agony caused by deficient service",
            "Misleading advertisements are punishable — company must deliver what is advertised",
            "You have the right to know the price, quality, and contents of any product",
            "Credit/debit card fraud — you are NOT liable if you reported it promptly",
            "Airlines, hotels, hospitals, schools are all covered under Consumer Protection Act",
            "You have 2 years from the date of issue to file a consumer complaint",
        ],
        "laws": ["Consumer Protection Act, 2019", "National Consumer Helpline Portal"],
        "helpline": ("Consumer Helpline", "1800-11-4000")
    },
    {
        "id": "property",
        "icon": "🏡",
        "title": "Property Rights",
        "color": "#1c2a1c",
        "accent": "#4ade80",
        "rights": [
            "Daughters have EQUAL right in ancestral Hindu property as sons (since 2005)",
            "A will can be challenged in court if made under pressure or by unsound mind",
            "No oral property transfer is valid — must be registered at Sub-Registrar office",
            "Sale through Power of Attorney (GPA) does not transfer ownership — SC ruling",
            "Property purchased during marriage is jointly owned by both spouses",
            "You can file a suit for partition to claim your share in joint family property",
            "Adverse possession — if you occupy land openly for 12+ years, you can claim title",
            "Benami property (in someone else's name) is illegal and can be confiscated",
            "You can check encumbrances on any property online at state registration portal",
            "NRI property rights are protected — power of attorney must be notarized",
        ],
        "laws": ["Hindu Succession Act, 1956 (amended 2005)", "Vineeta Sharma v. Rakesh Sharma (2020)", "Registration Act, 1908"],
        "helpline": ("NALSA Legal Aid", "1800-110-370")
    },
    {
        "id": "rti",
        "icon": "📋",
        "title": "RTI — Right to Information",
        "color": "#1a2535",
        "accent": "#38bdf8",
        "rights": [
            "Every citizen can ask ANY government department for information",
            "Fee is just ₹10 — free for Below Poverty Line (BPL) card holders",
            "Department MUST reply within 30 days (48 hours for life/liberty matters)",
            "You do not need to give any reason for asking information",
            "You can ask for documents, files, reports, contracts, sample of work",
            "If denied, you can file First Appeal within 30 days to same department",
            "Second Appeal goes to Central/State Information Commissioner — free",
            "False information or denial without reason is punishable by ₹250/day fine",
            "You can file RTI online at rtionline.gov.in",
            "Personal information of third parties may be exempted from disclosure",
        ],
        "laws": ["Right to Information Act, 2005", "CBSE v. Aditya Bandopadhyay (2011)"],
        "helpline": ("RTI Portal", "rtionline.gov.in")
    },
    {
        "id": "woman",
        "icon": "👩",
        "title": "Women's Special Rights",
        "color": "#2d1a2d",
        "accent": "#c084fc",
        "rights": [
            "Women have equal right to property, job, and education as men",
            "No woman can be arrested between 6 PM and 6 AM except in exceptional cases",
            "Woman's statement in rape case must be recorded by a female officer",
            "Maternity leave of 26 weeks is a legal right for working women",
            "Equal pay for equal work — gender pay gap is illegal",
            "POSH Act protects against sexual harassment at any workplace",
            "A woman can file for divorce on grounds of cruelty, desertion, or adultery",
            "You have right to alimony/maintenance even after divorce",
            "Acid attack victims are entitled to ₹3 lakh minimum compensation",
            "Stalking, voyeurism, and online harassment are criminal offences",
        ],
        "laws": ["Protection of Women from Domestic Violence Act, 2005", "POSH Act, 2013", "Criminal Law Amendment Act, 2013"],
        "helpline": ("Women Helpline 24/7", "1091")
    },
    {
        "id": "cyber",
        "icon": "💻",
        "title": "Cyber Crime Rights",
        "color": "#0f1f2d",
        "accent": "#06b6d4",
        "rights": [
            "Online fraud, hacking, identity theft are criminal offences under IT Act",
            "You can report cyber crime at cybercrime.gov.in or call 1930",
            "Sharing someone's private photos/videos without consent is punishable",
            "Cyberbullying and online stalking are covered under IT Act and IPC",
            "Bank/UPI fraud — report to bank within 3 days for zero liability",
            "You can demand removal of defamatory content from social media platforms",
            "Morphed photos or fake profiles using your identity is a crime",
            "You have the right to data privacy — companies must protect your personal data",
            "OTP fraud — you are NOT liable if you did not share OTP voluntarily",
            "Section 66A (sending offensive messages) was struck down — online speech is protected",
        ],
        "laws": ["Information Technology Act, 2000", "Shreya Singhal v. Union of India (2015)", "IT (Amendment) Act, 2008"],
        "helpline": ("Cyber Crime Helpline", "1930")
    },
    {
        "id": "child",
        "icon": "👶",
        "title": "Child Rights",
        "color": "#1f2d1f",
        "accent": "#86efac",
        "rights": [
            "Every child aged 6–14 has the RIGHT to free education (RTE Act)",
            "Child labour is illegal — children under 14 cannot work in any establishment",
            "Children under 18 cannot be tried as adults in most cases",
            "POCSO Act protects children from sexual abuse — any form of sexual contact is crime",
            "Every school must have a Child Protection Committee",
            "A child in conflict with law must be kept in Observation Home, NOT jail",
            "Birth registration is free and mandatory — no child can be denied it",
            "Child marriage is illegal — if you know of one, you can report it",
            "A child cannot be asked to sign a bond or confession",
            "Childline 1098 is free — call anytime for help for or about a child",
        ],
        "laws": ["Right to Education Act, 2009", "POCSO Act, 2012", "Juvenile Justice Act, 2015"],
        "helpline": ("Childline India 24/7", "1098")
    },
]
